### ISSUE TITLE
 AH00052: child pid [n] exit signal Segmentation fault (11)

### ISSUE THREAD

**Issue by paolobarra93** [lukec/stripe-perl#112]
Hi,

I installed from cpan your library with no error but in the apache's error_log i see this error:
 AH00052: child pid [n] exit signal Segmentation fault (11)
is it better include library or download and install from cpan? 

Thanks,
Paolo B

**Comment by andrewsolomon** [comment]
Hi Paolo,

I'm doubt that the problem you're encountering is related to Perl code other than possibly a memory leak due to circular references. I suggest looking into Apache, its configuration and how your OS is setup.

Sorry I couldn't offer more help!

Andrew
