### ISSUE TITLE
updated wording regarding API versioning

### ISSUE THREAD

**Issue by sherrardb** [lukec/stripe-perl#129]
https://github.com/lukec/stripe-perl/blob/b091f06825bdef4c895383c990c9e1187849331a/lib/Net/Stripe.pm#L58-L65

i am filing this as a separate issue so that it doesn't get lost in the shuffle of code review in the forthcoming pull request.

@andrewsolomon do you have any suggestions for:
- updates to the existing wording (above) regarding Net::Stripe being version-agnostic
- the detailed description of api_version attribute
my current draft of the latter is
```
=item api_version

This is the value of the Stripe-Version header you wish to transmit for API calls.
Because of non-backward-compatible changes in the Stripe API, this version of the SDK
is only guaranteed to support Stripe API versions 2012-10-26 through 2015-02-16,
inclusive.
```

ex, is "guaranteed to support" strong enough, or should we say "is known to be broken for API versions before... and after..."?

**Comment by andrewsolomon** [comment]
I'd change
```
=head2 WARNING
...
```
into
```
=head2 VERSIONING

Because of non-backward-compatible changes in the Stripe API, this version of the SDK
is only guaranteed to support Stripe API versions defined in C<Net::Stripe::Constants>... if you want a version of this supporting different versions look in <git branch...>

=head3 DEFAULT VERSIONING

When you don't set the version on object instantiation you're just using your account's default version...

=head3 SPECIFIC VERSIONING

When you set a version on object instantiation you're telling Stripe to use that version of the API instead of your account's default version...

=head3 OUT OF SCOPE VERSIONING

If you're wearing a cowboy hat and think - although your account version is outside the range defined in  C<Net::Stripe::Constants> - your use case is simple enough that it should "just work", create your object instance with C<<force_version => ... >> and don't say I didn't warn you!

=cut
```

**Comment by sherrardb** [comment]
wonderful :-)

i definitely like the idea of changing the attribute to `force_version`, but i think i favor the more-descriptive `force_api_version`, which i hope is in keeping with your intentions.

**Comment by sherrardb** [comment]
nevermind the second part. i think i have conflated two separate issues. it seems that `force_version` is the same as `ignore_version` that you suggested on the PR. i'll submit my changes and you can clarify if i am barking up the wrong tree.
