### ISSUE TITLE
refund_charge doesn't work?

### ISSUE THREAD

**Issue by yahermann** [lukec/stripe-perl#44]
There appears to be a bug with refund_charge.  I'm getting the following error:

Can't locate object method "new" via package "Net::Stripe::Refund" (perhaps you forgot to load "Net::Stripe::Refund"?) at /usr/local/share/perl/5.18.2/Net/Stripe.pm line 708

Reviewing the module manifest, there is no Net::Stripe::Refund, and looking at Stripe.pm line ~708, I see where there is a reference to a possible non-existent "Net::Stripe::Refund" if $object = "Refund".

Reviewing the Stripe API documentation, a Create Refund is supposed to return a Refund object:
https://stripe.com/docs/api#create_refund

whereas the Net::Stripe documentation specifies that a call to refund_charge will return a Charge object.... so there's an inconsistency.

I'm using the very latest version of stripe-perl (version 0.25), which I just upgraded to, to make sure the bug could be easily replicated.

Thanks in advance for any assistance!

**Comment by rustyconover** [comment]
Hi,

Thanks for the bug report.  It seems that Net::Stripe::Refund is indeed unimplemented.

I personally haven't had a need to create refunds in Stripe, but when I do I plan on implementing this code, in the meantime if you need this code sooner than that indeterminate timeframe.  You could work up a pull request, by taking the structure from Charge.pm and modifying it to use the fields for a refund.   Then hook up the various methods in Stripe.pm based on what you find there already under the charge section.  I'm happy to answer any questions.

Rusty

**Comment by yahermann** [comment]
Hi Rusty,

I'm intermediate at Perl and had never had the honor to contribute to an open-source project like this one, but I'm happy to try.  I'll spend some time on it with the hints you suggested, and follow up.  Cheers!

**Comment by yahermann** [comment]
Hi Rusty, I think I got it working.  Works on my end anyway.  I sent a pull request.  Feedback/comments greatly welcomed!

**Comment by rustyconover** [comment]
This looks great, see my notes on the pull request for a few changes and I'll merge it later this evening.  

Do you have any test cases?

**Comment by rustyconover** [comment]
Released new code in 0.27 to CPAN.
