### ISSUE TITLE
No update_* methods?

### ISSUE THREAD

**Issue by moltar** [lukec/stripe-perl#49]
Is there a reason why this module does not have `update_*` methods? Is it just not implemented, or is there a limitation? Thanks!

**Comment by NacreData** [comment]
I'm not aware of any inherent limitation; Anything possible through the API should be able to be implemented. Feel free to submit a pull request or ask for help if you have something almost working and need an extra set of eyes.

**Comment by sherrardb** [comment]
just updating for the sake of posterity. @NacreData is correct. for currently supported object types, all API functionality should be implemented. you may find is that for some object types update_* is handled via post_* with the appropriate arguments, where other object types have dedicated update_* methods.

and if you find something lacking, please submit a pull request containing a failing test and the proposed patch.
