### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by ausmani** [lukec/stripe-perl#65]
You didn't tell any idea how to get the token ?

**Comment by zachwick** [comment]
`Token` objects are usually created using Stripe Checkout or Stripe.js (https://stripe.com/docs/checkout and https://stripe.com/docs/stripe.js respectively).

Alternatively, you can create a `Token` using the `/v1/tokens` API endpoint via the Token methods in this library (https://github.com/lukec/stripe-perl#token-methods).

The former option shifts much of the burden of PCI compliance onto Stripe as no raw credit card information ever hits your server.
