### ISSUE TITLE
get_cards issue

### ISSUE THREAD

**Issue by youradds** [lukec/stripe-perl#78]
Hi,

There seems to be a bug with get_cards():

    use Net::Stripe;
    my $stripe = Net::Stripe->new(
        api_key => $CFG->{stripe_mode} eq "test" ? $CFG->{stripe_secret_test} : $CFG->{stripe_secret_live},
        debug         => '1',
        debug_network => '1'
     );

     my $cards = $stripe->get_cards(customer => 'cus_ALXYaoa9Lpo4Gs',  limit => 10);

...causes:

Odd number of elements in anonymous hash at test.cgi line 35.

Line 35 is this:

     my $cards = $stripe->get_cards(customer => 'cus_ALXYaoa9Lpo4Gs',  limit => 10);

If I did into the code being run, it fails on this bit in Net::Strip.pm:

    method get_cards(Net::Stripe::Customer|Str $customer,
                     HashRef :$created?,
                     Str :$ending_before?,
                     Int :$limit?,
                     Str :$starting_after?) {

I've checked this in SSH as well, so there wont be any issues such as mod_perl getting in the way. 

Perl v5.22.1

Here is the thread where I tried to fix it myself, but I'm coming up black:

http://perlmonks.org/?node_id=1187759

I'd appreciate if someone could get a fix, as this is holding up my whole payment system :( (I was using another module, but it didn't have the flexibility I needed, whereas this one would... if I can get it working)

**Comment by andrewsolomon** [comment]
I've not looked into your issue in detail, but there are a couple of points about Net::Stripe worth noting:
* As you'll see here https://metacpan.org/pod/Net::Stripe the CPAN code hasn't been updated for quite some time, so you might have more luck working with what's in GitHub's master branch
* This more recently published module https://metacpan.org/pod/Net::Stripe::Simple#cards appears to be simpler and may turn out to be easier to work with.

Hope that helps!

**Comment by youradds** [comment]
Thanks. I'm actually using the github version :) 

I tried to install the cpanm version of Net::Stripe::Simple, but I get an error:

```
t/00-report-prereqs.t .... ok
t/author-pod-coverage.t .. skipped: these tests are for testing by the author
t/author-pod-syntax.t .... skipped: these tests are for testing by the author
    # No tests run!

#   Failed test 'No tests run for subtest "Recipients"'
#   at t/basic.t line 685.
Error: invalid_request_error - Recipients have been deprecated and are no longer available. They have been replaced by managed accounts (see https://stripe.com/docs/connect/managed-accounts), which you should use if you're creating a ne$
t/basic.t ................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/20 subtests
t/data.t ................. ok
t/errors.t ............... ok
t/release-unused-vars.t .. skipped: these tests are for release candidate testing

Test Summary Report
-------------------
t/basic.t              (Wstat: 65280 Tests: 14 Failed: 1)
  Failed test:  14
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 20 tests but ran 14.
Files=8, Tests=29, 39 wallclock secs ( 0.10 usr  0.03 sys +  3.63 cusr  0.32 csys =  4.08 CPU)
Result: FAIL
Failed 1/8 test programs. 1/29 subtests failed.
Makefile:872: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
-> FAIL Installing Net::Stripe::Simple failed. See /root/.cpanm/work/1492091699.2574/build.log for details. Retry with --force to force install it.
Expiring 1 work directories.
```

I'm not too sure what that even means?

**Comment by youradds** [comment]
This is stupid. There IS a bug with this module in later version of Perl, but I just don't know enough about its inners to work it out!  

Perl v5.22.1

REALLY simple test:

```
use Net::Stripe;
my $stripe     = Net::Stripe->new(api_key => $key);

my $foo = $stripe->get_customer($USER->{stripe_customer_id});

```
gives:

> Sat Apr 29 07:47:05 2017] test.cgi: Odd number of elements in anonymous hash at test.cgi line 25.

Line 25 is the my $foo ... line

Even other functions give the exact same error:

`my $foo = $stripe->list_subscriptions($USER->{stripe_customer_id});`

PLEASE will someone look into this? It's driving me nuts!!!!

**Comment by andrewsolomon** [comment]
Regarding the issues in your most recent message - I think they are all because you're not using named parameters. It should me something like:
```
$stripe->get_customer(customer_id => $customer->id);
```
If you find the documentation unclear, seeing how it's done in t/live.t can be helpful.

As to the get_cards problem at the beginning of this thread, it was a bug. I think this fixes it https://github.com/lukec/stripe-perl/pull/79/files

Can you confirm that this resolves your issue? Please test it out on https://github.com/andrewsolomon/stripe-perl

If you're happy, I'll accept the pull request and do a new release.

**Comment by youradds** [comment]
Thanks for the reply @andrewsolomon . I've actually already done the fix to get_card(), but that didn't fix it :( 

Does it work ok for you on Perl 5.22.1? Latest Kavorka?

**Comment by andrewsolomon** [comment]
Hi @youradds,

When you say "already done the fix to get_card", I assume you mean get_card**s** since that's the method you were reporting on at the outset. Since I haven't seen your fix for Net::Stripe I can't say what's wrong so could you please work against the Net::Stripe I've provided here https://github.com/andrewsolomon/stripe-perl

If you still have a bug the next step is to run
```
STRIPE_API_KEY=sk_test_YOUR_PRIVATE_TEST_KEY prove -lv t/live.t
```
and copy and paste any "not ok"s

Thanks

Andrew

**Comment by youradds** [comment]
Hi @andrewsolomon  - Ah man, I must have been missing something - that now works like a charm :) (I re-uploaded the  whole thing from git).

For anyone else who comes across this, the formats are like:

```

my $stripe     = Net::Stripe->new(api_key => "sk_test_key");
my $cards = $stripe->get_cards(customer => "cus_ALXYaoa9Lpo4Gs");
my $customer $stripe->get_customer(customer_id => "cus_ALXYaoa9Lpo4Gs");
```

etc

Maybe it would be good to add some kinda error reporting when someone (ahem, like me :)), doesn't pass in an expected param? Such as, I was trying to just pass in a string:
```
$stripe->get_cards("cus_ALXYaoa9Lpo4Gs");
```

...which now I know wasn't right, but has caused me tons and tons of extra work trying to debug it, when it was actually me just being a muppet :( 

Thanks!

Andy

**Comment by andrewsolomon** [comment]
Thanks for checking that it works @youradds. I've just released in onto cpan https://metacpan.org/release/ILLY/Net-Stripe-0.32 and you'll be able to install it with cpanm in the next couple of hours.

Regarding the uninformative error messages, I'm sure that any suggestions would be welcomed by
Toby who developed the Kavorka package. https://metacpan.org/pod/Kavorka

**Comment by youradds** [comment]
Thanks :)
