### ISSUE TITLE
Not passing starting_after

### ISSUE THREAD

**Issue by rmiller-fb** [lukec/stripe-perl#83]
Hi.  Passing in starting_after to get_customers was not having the documented effect.  I added the following to sub_get_collections:

    if (my $c = $args{starting_after}) {
        push @path_args, "starting_after=$c";
    }

... and now it works.  Is there something I'm not getting?

**Comment by andrewsolomon** [comment]
It could be that you're the first to use this "feature" :-) If could add a unit test which demonstrates this bug and also your fix to a pull request, that would be greatly appreciated!

**Comment by slobo** [comment]
We just got hit with the same bug, and proposed solution works

**Comment by andrewsolomon** [comment]
Thank you very much Slobodan! Net-Stripe-0.34 should appear [here](https://metacpan.org/pod/Net::Stripe) in the next couple of hours.
