### ISSUE TITLE
verify that test scripts are using a test mode key

### ISSUE THREAD

**Issue by sherrardb** [lukec/stripe-perl#90]
based on an aborted test script run, i thought to add an idiom to the test script that deletes all customers of the form that we are adding with the test script (name=> 'Anonymous').

my next thought was "what if this goes wrong for the user and/or is being run with the live mode key?" cleaning up errant transactions is one thing. losing one's customer list is another.  at the simplest, we could test for `$api_key =~ /^sk_test_.+/`. a more-robust test would be to post a small charge, and confirm `livemode==0` for the object returned.

**Comment by andrewsolomon** [comment]
I've done the simple test. If live api keys crop up with the format /^sk_test_.*/ I'll be looking for a different payment provider :-)
